#!/usr/bin/env bash

tmux_running=$(pgrep tmux)

if [[ -z $tmux_running ]] || !(tmux has-session -t "cozy-park" 2>/dev/null); then
    tmux new-session -d -s cozy-park -n Vim 
fi

tmux send-keys -t cozy-park:0 'vim .' C-m

tmux new-window -t cozy-park:1 -n Server
tmux send-keys -t cozy-park:1 'cd cmd && air' C-m

tmux split-window -t cozy-park:1 -h
tmux send-keys -t cozy-park:1 'npx live-server web -p 8080' C-m

tmux attach-session -t cozy-park
